export const PATH = {
  ROOT: '/',
  SIGN_IN: '/signin',
  SIGN_FIND_ID: '/signin/find/id',
  SIGN_FIND_PW: '/signin/find/pw',
  SIGN_UP: '/signup',
  SIGN_UP_TYPE: (type = ':type') => `/signup/step/${type}`,
  SIGN_UP_FORM: (type = ':type') => `/signup/step/${type}/form`,
  SIGN_UP_DONE: (type = ':type') => `/signup/step/${type}/done`,
  STRATEGIES_LIST: '/strategies',
  STRATEGIES_DETAIL: (strategyId = ':strategyId') =>
    `/strategies/${strategyId}`,
  ADD_QNA: (strategyId = ':strategyId') => `/strategies/${strategyId}/qna/add`,
  TRADERS: '/traders',
  TRADER_STRATEGIES: (userId = ':userId') => `/traders/${userId}`,
  STRATEGIES_SEARCH: '/strategies/search',
  STRATEGIES_INFO_TRADER: '/strategies/info/trader',
  STRATEGIES_ADD: '/strategies/add',
  MYPAGE: '/mypage',
  MYPAGE_CHECK: '/mypage/check',
  MYPAGE_PROFILE: '/mypage/profile',
  MYPAGE_PROFILE_EDIT: '/mypage/profile/edit',
  MYPAGE_QNA_USER: '/mypage/user/qna',
  MYPAGE_QNA_TRADER: '/mypage/trader/qna',
  MYPAGE_QNA_EDIT: (qnaId = ':qnaId') => `/mypage/qna/${qnaId}/edit`,
  MYPAGE_WITHDRAW: '/mypage/withdraw',
  MYPAGE_INTERESTS: '/mypage/interests',
  MYPAGE_STRATEGIES: '/mypage/strategies',
  MYPAGE_STRATEGIES_EDIT: (strategyId = ':strategyId') =>
    `/mypage/strategies/${strategyId}`,
  ADMIN: '/admin',
  ADMIN_USERS: '/admin/users',
  ADMIN_NOTICES: '/admin/notices',
  ADMIN_NOTICES_ADD: '/admin/notices/add',
  ADMIN_NOTICES_EDIT: (noticeId = ':noticeId') =>
    `/admin/notices/${noticeId}/edit`,
  ADMIN_STOCKS: '/admin/stocks',
  ADMIN_METHODS: '/admin/methods',
  ADMIN_STRATEGIES: '/admin/strategies',
  ADMIN_QNA: '/admin/qna',
  NOTICES: '/notices',
  NOTICES_DETAIL: (noticeId = ':noticeId') => `/notices/${noticeId}`,
  FAQ: '/faq',
  TEMP: '/temp',
  NOT_FOUND: '*',
};
